# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticos',
            name='observaciones',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
