# Generated by Django 3.1.6 on 2021-02-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_consulta', models.IntegerField()),
                ('fecha_consulta', models.DateField()),
                ('edad_gestacional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('altura_uterina', models.IntegerField()),
                ('FCF', models.IntegerField()),
                ('freq_respiratoria', models.IntegerField()),
                ('glucemia', models.IntegerField()),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.datos_personas')),
            ],
        ),
    ]
