# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_consulta', models.IntegerField()),
                ('fecha_consulta', models.DateField()),
                ('edad_gestacional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('altura_uterina', models.IntegerField()),
                ('FCF', models.IntegerField()),
                ('freq_respiratoria', models.IntegerField()),
                ('glucemia', models.IntegerField()),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.Datos_Personas')),
            ],
        ),
    ]
