# Generated by Django 3.1.6 on 2021-02-15 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Amarillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUM', models.DateField()),
                ('FPP', models.DateField()),
                ('tipo_sangre', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], default='O+', max_length=5)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('talla', models.IntegerField()),
                ('etnia', models.CharField(max_length=10)),
                ('fecha_embarazo_anterior', models.DateField(blank=True)),
                ('estudios', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('BACHILLERATO', 'Bachillerato'), ('UNIVERSIDAD', 'Universidad'), ('POSGRADO', 'Posgrado')], default='PRIMARIA', max_length=15)),
                ('cantidad_fetos', models.IntegerField()),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.datos_personas')),
            ],
        ),
    ]
