# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre_enfermedad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
