# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-27 02:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_Amarillo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FUM', models.DateField()),
                ('FPP', models.DateField()),
                ('tipo_sangre', models.CharField(choices=[('A-', 'A-'), ('A+', 'A+'), ('B-', 'B-'), ('B+', 'B+'), ('AB-', 'AB-'), ('AB+', 'AB+'), ('O-', 'O-'), ('O+', 'O+')], default='O+', max_length=2)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('talla', models.IntegerField()),
                ('etnia', models.CharField(max_length=10)),
                ('fecha_embarazo_anterior', models.DateField(blank=True)),
                ('estudios', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('BACHILLERATO', 'Bachillerato'), ('UNIVERSIDAD', 'Universidad'), ('POSGRADO', 'Posgrado')], default='PRIMARIA', max_length=15)),
                ('cantidad_fetos', models.IntegerField()),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.Datos_Personas')),
            ],
        ),
    ]
