# Generated by Django 3.1.6 on 2021-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelos2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30)),
                ('peso', models.IntegerField()),
                ('presion_sistolica', models.IntegerField()),
                ('presion_diastolica', models.IntegerField()),
                ('pulso_cardiaco', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('pentavalente', models.BooleanField()),
                ('difterica', models.BooleanField()),
                ('edad', models.IntegerField()),
                ('embarazo_previo', models.BooleanField()),
                ('diagnostico', models.BooleanField()),
            ],
        ),
    ]
