# Generated by Django 3.1.6 on 2021-02-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
        ('modelPregnancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelos2',
            name='folio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.datos_personas'),
        ),
    ]
