# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='domicilio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
