# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amarilla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parejas_sexuales', models.IntegerField()),
                ('gestas_previas', models.IntegerField()),
                ('partos', models.IntegerField()),
                ('abortos', models.IntegerField()),
                ('cesareas', models.IntegerField()),
                ('vaginales', models.IntegerField()),
                ('nacidos_vivos', models.IntegerField()),
                ('viven', models.IntegerField()),
            ],
        ),
    ]
