# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-21 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_person_domicilio'),
        ('general', '0001_initial'),
        ('preg_historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_consulta', models.IntegerField()),
                ('fecha_consulta', models.DateField()),
                ('edad_gestacional', models.DecimalField(decimal_places=2, max_digits=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=20)),
                ('altura_uterina', models.IntegerField()),
                ('FCF', models.IntegerField()),
                ('freq_respiratoria', models.IntegerField()),
                ('glucemia', models.IntegerField()),
                ('folio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Inmunizaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacunas', models.ManyToManyField(to='general.Vacunas')),
            ],
        ),
        migrations.AddField(
            model_name='amarilla',
            name='folio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personal_data.Person'),
        ),
    ]
