# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-03-09 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('father_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial_padres',
            name='apellido_materno',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial_padres',
            name='apellido_paterno',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historial_padres',
            name='nombre',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
