# Generated by Django 3.1.6 on 2021-02-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre_enfermedad', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
